### ISSUE TITLE
how to facilitate the proper interpretation of p-values when multiple tests are performed

### ISSUE THREAD

**Issue by tompollard** [tompollard/tableone#23]
ref: https://github.com/tompollard/tableone/issues/19

> the inclusion of p-values does not consider multiple testing and false discover rate issues.

> ...Possible approaches include providing facilities to (self)identify ... whether p-values are corrected or when p-values should be corrected for multiple testing. Try to go the next step and prevent possible misinterpretation of data.

**Comment by jraffa** [comment]
As discussed IRL, it is unclear if the concern of multiple testing is from:
- pairwise (column/group level) tests when the number of groups are large, or 
- when the number of rows may be large.

Since the package currently doesn't do any pairwise tests, I would say the latter.

It looks like https://github.com/tompollard/tableone/commit/3cd789ac2fc24e294b90216a0d544fce70e65cd5 adds a Bonferroni correction for this. (If I'm reading the python correctly.

**Comment by tompollard** [comment]
Thanks Jesse, and that's correct - the Bonferroni correction has been added for multiple comparison of rows, and I'll add additional correction methods shortly. We don't offer group (column) level comparisons at the moment, so I assume this was not the reviewer's concern.

There is an argument for removing p-values altogether, but people will want to compute them regardless so it feels better to offer the functionality and then try to use the package to promote good practice.

**Comment by tompollard** [comment]
At the moment, corrected p-values are displayed in a new `pval_adjust` column, alongside the unadjusted `pval` column. 

Instead, perhaps there should be a single column for pvalues? This would display unadjusted values when no adjustment is applied, and adjusted values when an adjustment is applied.

**Comment by jraffa** [comment]
I would keep the columns separate, as I think it would be easier to drop one.

Having a second column for p-values pretty common in (for e.g., ) GEE where there's a "Naive" and a "Robust" analysis.  I would keep the adjusted/non-adjusted naming however.
